version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'helm'
    directory: '/charts'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'cargo'
    directory: '/.dummy'
    schedule:
      interval: 'weekly'
