apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scheduler.fullname" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  {{- if not .Values.scheduler.autoscaling.enabled }}
  replicas: {{ .Values.scheduler.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.scheduler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scheduler.labels" . | nindent 8 }}
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.scheduler.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scheduler.serviceAccountName" . }}
      {{- with .Values.scheduler.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "guggr.waitForPostgres" . | nindent 8 }}
        {{- include "guggr.waitForRabbitMQ" . | nindent 8 }}
      containers:
        - name: {{ include "scheduler.name" . }}
          {{- with .Values.scheduler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          {{- with .Values.scheduler.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduler.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduler.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          - name: RABBITMQ_HOST
            value: {{ include "guggr.rabbitmqHost" . | quote }}
          - name: RABBITMQ_PORT
            value: {{ .Values.global.rabbitmq.port | toString | quote }}
          - name: RABBITMQ_JOBS_QUEUE
            value: {{ .Values.global.rabbitmq.jobsQueue | toString | quote }}
          - name: RABBITMQ_USER
            value: {{ .Values.global.rabbitmq.auth.username | toString | quote }}
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.rabbitmq.auth.secretName | quote }}
                key: {{ .Values.global.rabbitmq.auth.passwordKey | quote }}
          - name: POSTGRES_HOST
            value: {{ include "guggr.postgresHost" . | quote }}
          - name: POSTGRES_PORT
            value: {{ .Values.global.postgres.port | toString | quote }}
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.auth.secretName | quote }}
                key: {{ .Values.global.postgres.auth.databaseKey | quote }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.auth.secretName | quote }}
                key: {{ .Values.global.postgres.auth.usernameKey | quote }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.auth.secretName | quote }}
                key: {{ .Values.global.postgres.auth.passwordKey | quote }}
          - name: RUST_LOG
            value: {{ .Values.scheduler.logLevel | toString | quote }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
