fail_fast: true

default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/crate-ci/typos
    rev: v1.42.3
    hooks:
      - id: typos
        exclude: CHANGELOG.md # Recognized commit SHAs as typos

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: local
    hooks:
      - id: prettier-check
        name: run pnpm check
        language: system
        entry: pnpm run check
        pass_filenames: false

      - id: trufflehog
        name: run trufflehog
        entry: bash -c  'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ['commit', 'push']

      - id: helm-lint
        name: run helm lint
        language: system
        entry: helm lint charts/guggr
        pass_filenames: false
        files: ^charts/

      - id: helm-gen-readme
        name: generate helm chart readme
        language: system
        entry: pnpm gen:helm-readme
        pass_filenames: false
        files: ^charts/

      - id: cargo-fmt
        name: run cargo fmt
        types: [rust]
        language: system
        entry: rustfmt-nightly
        pass_filenames: false

      - id: cargo-clippy
        name: run clippy
        types: [rust]
        language: system
        entry: cargo clippy --all-features --all-targets -- -D warnings
        pass_filenames: false

      - id: cargo-nextest
        name: run cargo nextest
        types: [rust]
        language: system
        entry: cargo nextest run --no-tests warn
        pass_filenames: false

      - id: cargo-autoinherit
        name: run cargo autoinherit
        types: [rust]
        language: system
        entry: cargo autoinherit
        pass_filenames: false

      - id: cargo-machete
        name: run cargo machete
        types: [rust]
        language: system
        entry: cargo machete
        pass_filenames: false

      - id: api-service-check-spec
        name: check openapi spec
        files: ^api-service/
        language: system
        entry: api-service/openapi-check.sh
        pass_filenames: false
