singleQuote: true
arrowParens: avoid
printWidth: 100
useTabs: true
plugins:
  - prettier-plugin-astro
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
  - prettier-plugin-sql
overrides:
  - files: '*.sql'
    options:
      language: 'postgresql'
