replicaCount: 1

image:
  repository: ghcr.io/guggr/guggr/evaluator
  pullPolicy: IfNotPresent

imagePullSecrets: []

fullnameOverride: ""
nameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

autoscaling:
  enabled: false

nodeSelector: {}

resources: {}

tolerations: []

affinity: {}
