Table job [headercolor: #175e7a] {
	id text [ not null, note: 'Nano ID' ]
	name text [ not null ]
	job_type_id text [ not null ]
	group_id text [ not null ]
	notify_users boolean [ not null ]
	custom_notification text
	run_every interval [ not null ]
	last_scheduled timestamp
}

Table user [headercolor: #175e7a] {
	id text [ not null, note: 'Nano ID' ]
	name text [ not null ]
	email text [ not null ]
	password text [ not null ]
	jwt_secret bytea [ not null ]
}

Table group [headercolor: #175e7a] {
	id text [ not null, note: 'Nano ID' ]
	name text [ not null ]
}

Table user_group_mapping [headercolor: #175e7a] {
	user_id text [ not null ]
	group_id text [ not null ]
	role_id text [ not null, default: 'user' ]
}

Table role [headercolor: #175e7a] {
	id text [ not null ]
	name text [ not null ]
}

Table job_runs [headercolor: #175e7a] {
	id text [ not null, note: 'Nano ID' ]
	job_id text [ not null ]
	timestamp timestamp [ not null ]
	triggered_notification boolean [ not null ]
	batch_id text [ not null ]
	reachable boolean [ not null ]
}

Table job_type [headercolor: #175e7a] {
	id text [ not null ]
	name text
}

Table job_details_http [headercolor: #175e7a] {
	id text [ not null ]
	url text [ not null ]
}

Table job_details_ping [headercolor: #175e7a] {
	id text [ not null ]
	host text [ not null ]
}

Table job_result_ping [headercolor: #175e7a] {
	id text [ not null ]
	ip_address inet [ not null ]
	latency integer [ not null ]
}

Table job_result_http [headercolor: #175e7a] {
	id text [ not null ]
	ip_address inet [ not null ]
	status_code integer [ not null ]
	latency integer [ not null ]
	payload bytea [ not null ]
}

Table refresh_token [headercolor: #175e7a] {
	token text [ not null ]
	user_id text [ not null ]
	expires_on timestamp [ not null ]
}

Ref fk_job_group_id_group {
	job.group_id > group.id [ delete: cascade, update: cascade ]
}

Ref fk_user_group_mapping_group_id_group {
	user_group_mapping.group_id > group.id [ delete: restrict, update: cascade ]
}

Ref fk_user_group_mapping_user_id_user {
	user_group_mapping.user_id > user.id [ delete: restrict, update: cascade ]
}

Ref fk_user_group_mapping_role_id_role {
	user_group_mapping.role_id > role.id [ delete: set default, update: cascade ]
}

Ref fk_job_runs_job_id_job {
	job_runs.job_id > job.id [ delete: cascade, update: cascade ]
}

Ref fk_job_job_type_id_job_type {
	job.job_type_id > job_type.id [ delete: restrict, update: cascade ]
}

Ref fk_job_details_http_id_job {
	job_details_http.id > job.id [ delete: no action, update: no action ]
}

Ref fk_job_details_http_id_job {
	job_details_http.id > job.id [ delete: cascade, update: cascade ]
}

Ref fk_job_details_ping_id_job {
	job_details_ping.id > job.id [ delete: no action, update: no action ]
}

Ref fk_job_details_ping_id_job {
	job_details_ping.id > job.id [ delete: cascade, update: cascade ]
}

Ref fk_job_result_ping_id_job_runs {
	job_result_ping.id > job_runs.id [ delete: cascade, update: cascade ]
}

Ref fk_job_result_http_id_job_runs {
	job_result_http.id > job_runs.id [ delete: cascade, update: cascade ]
}

Ref fk_refresh_token_user_id_user {
	refresh_token.user_id > user.id [ delete: cascade, update: cascade ]
}
