server {
    server_tokens   off;

    listen       8080;
    server_name  localhost;
    absolute_redirect off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}
