global:
  ## @section Global RabbitMQ parameters
  ## @descriptionStart
  ## These parameters are used by the `agent`, `evaluator` and `scheduler` Subcharts
  ## @descriptionEnd
  rabbitmq:
    ## @param global.rabbitmq.host Global RabbitMQ set to this charts' `rabbitmq.fullname` by default
    host: ""
    ## @param global.rabbitmq.port Global RabbitMQ AMQP port
    port: 5672
    ## @param global.rabbitmq.jobsQueue queue for jobs. Must match the definition in [rabbitmq_definitions.json](files/rabbitmq_definitions.json) when using the bundled RabbitMQ chart
    jobsQueue: scheduler.jobs
    ## @param global.rabbitmq.jobResultQueue queue for job results. Must match the definition in [rabbitmq_definitions.json](files/rabbitmq_definitions.json) when using the bundled RabbitMQ chart
    jobResultQueue: agent.job_results
    auth:
      ## @param global.rabbitmq.auth.username Username of the RabbitMQ User
      username: guggr
      ## @param global.rabbitmq.auth.secretName Name of existing Secret containing the RabbitMQ Users' Password
      secretName: guggr-rabbitmq
      ## @param global.rabbitmq.auth.passwordKey Key in existing Secret containing the RabbitMQ Users' Password
      passwordKey: password
  ## @section Global Postgres parameters
  ## @descriptionStart
  ## These parameters are used by the `api-service`, `evaluator` and `scheduler` Subcharts
  ## @descriptionEnd
  postgres:
    ## @param global.postgres.host Global Postgres Host, set to this charts' `postgres.fullname` by default
    host: ""
    ## @param global.postgres.port Global Postgres Port
    port: 5432
    auth:
      ## @param global.postgres.auth.secretName Name of existing Secret containing the Postgres Username, Password and Database Name
      secretName: guggr-postgres
      ## @param global.postgres.auth.usernameKey Key in existing Secret containing the Postgres Username
      usernameKey: username
      ## @param global.postgres.auth.passwordKey Key in existing Secret containing the Postgres Users' Password
      passwordKey: postgres-password
      ## @param global.postgres.auth.databaseKey Key in existing Secret containing the Postgres Database
      databaseKey: database

## @section Api-service Parameters
api-service:
  ## @param api-service.enabled Enable the Api-service
  enabled: true
  ## @param api-service.replicaCount Number of Api-service replicas to deploy
  replicaCount: 1

  ## @param api-service.image Optional image override for the Api-service container.
  image: {}
    ## @param api-service.image.repository [default: ghcr.io/guggr/guggr/api-service] Override the image repository.
    ## @param api-service.image.tag [default: AppVersion] Override the image tag.

  ## @section Api-service Ingress
  ingress:
    ## @param api-service.ingress.enabled Enable ingress for the Api-service
    enabled: false
    ## @param api-service.ingress.className Ingress class name
    className: ""
    ## @param api-service.ingress.annotations Ingress annotations
    annotations: {}
    ## @param api-service.ingress.hosts [object] Ingress hosts configuration
    hosts:
      - host: guggr.internal
        paths:
          - path: /api
            pathType: Prefix
    ## @param api-service.ingress.tls Ingress TLS configuration
    tls: []

  ## @section Api-service HTTPRoute
  httpRoute:
    ## @param api-service.httpRoute.enabled Enable Gateway API HTTPRoute generation for the Api-service
    enabled: false
    ## @param api-service.httpRoute.annotations Additional annotations for the HTTPRoute resource
    annotations: {}
    ## @param api-service.httpRoute.parentRefs [array] References to the parent Gateways
    parentRefs:
      - name: ""
        namespace: ""
        sectionName: ""
    ## @param api-service.httpRoute.hostnames List of hostnames to match
    hostnames: []
    ## @param api-service.httpRoute.rules [array] HTTPRoute rules
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

## @section Frontend Parameters
frontend:
  ## @param frontend.enabled Enable the Frontend
  enabled: true
  ## @param frontend.replicaCount Number of Frontend replicas to deploy
  replicaCount: 1

  ## @param frontend.image Optional image override for the Frontend container.
  image: {}
    ## @param frontend.image.repository [default: ghcr.io/guggr/guggr/frontend] Override the image repository.
    ## @param frontend.image.tag [default: AppVersion] Override the image tag.

  ## @section Frontend Ingress
  ingress:
    ## @param frontend.ingress.enabled Enable ingress for the Frontend
    enabled: false
    ## @param frontend.ingress.className Ingress class name
    className: ""
    ## @param frontend.ingress.annotations Ingress annotations
    annotations: {}
    ## @param frontend.ingress.hosts [object] Ingress hosts configuration
    hosts:
      - host: guggr.internal
        paths:
          - path: /
            pathType: Prefix
    ## @param frontend.ingress.tls Ingress TLS configuration
    tls: []

  ## @section Frontend HTTPRoute
  httpRoute:
    ## @param frontend.httpRoute.enabled Enable Gateway API HTTPRoute generation for the Frontend
    enabled: false
    ## @param frontend.httpRoute.annotations Additional annotations for the HTTPRoute resource
    annotations: {}
    ## @param frontend.httpRoute.parentRefs [array] References to the parent Gateways
    parentRefs:
      - name: ""
        namespace: ""
        sectionName: ""
    ## @param frontend.httpRoute.hostnames List of hostnames to match
    hostnames: []
    ## @param frontend.httpRoute.rules [array] HTTPRoute rules
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

## @section Agent Parameters
agent:
  ## @param agent.enabled Enable the Agent
  enabled: true
  ## @param agent.replicaCount Number of Agent replicas to deploy
  replicaCount: 1
  ## @param agent.image Optional image override for the Agent container.
  image: {}
    ## @param agent.image.repository [default: ghcr.io/guggr/guggr/agent] Override the image repository.
    ## @param agent.image.tag [default: AppVersion] Override the image tag.

## @section Evaluator Parameters
evaluator:
  ## @param evaluator.enabled Enable the Evaluator
  enabled: true
  ## @param evaluator.replicaCount Number of Evaluator replicas to deploy
  replicaCount: 1
  ## @param evaluator.image Optional image override for the Evaluator container.
  image: {}
    ## @param evaluator.image.repository [default: ghcr.io/guggr/guggr/evaluator] Override the image repository.
    ## @param evaluator.image.tag [default: AppVersion] Override the image tag.

## @section Scheduler Parameters
scheduler:
  ## @param scheduler.enabled Enable the Scheduler
  enabled: true
  ## @param scheduler.replicaCount Number of Scheduler replicas to deploy
  replicaCount: 1
  ## @param scheduler.image Optional image override for the Scheduler container.
  image: {}
    ## @param scheduler.image.repository [default: ghcr.io/guggr/guggr/scheduler] Override the image repository.
    ## @param scheduler.image.tag [default: AppVersion] Override the image tag.

## @section Postgres Parameters
postgres:
  ## @param postgres.enabled Enable the bundled Postgres Subchart
  enabled: true
  ## @param postgres.replicaCount Number of PostgreSQL replicas to deploy (Note: PostgreSQL doesn't support multi-master replication by default)
  replicaCount: 1
  auth:
    ## @param postgres.auth.username Name for default User that is created at startup
    username: guggr
    ## @param postgres.auth.database Name for default Database that is created at startup
    database: guggr

## @section RabbitMQ Parameters
rabbitmq:
  ## @param rabbitmq.enabled Enable the bundled RabbitMQ Subchart
  enabled: true
  ## @param rabbitmq.replicaCount Number of RabbitMQ replicas to deploy (clustering needs to be enabled to set more than 1 replicas)
  replicaCount: 1

  auth:
    ## @param rabbitmq.auth.enabled Enable RabbitMQ Authentication
    enabled: true
    ## @param rabbitmq.auth.username RabbitMQ default username
    username: guggr

  managementPlugin:
    ## @param rabbitmq.managementPlugin.enabled Enable RabbitMQ management plugin
    enabled: false

  ## @param rabbitmq.extraVolumes [array] Extra volumes to add to RabbitMQ pods
  extraVolumes:
    - name: definitions
      configMap:
        name: rabbitmq-definitions

  ## @param rabbitmq.extraVolumeMounts [array] Extra volumes to add to RabbitMQ pods
  extraVolumeMounts:
    - name: definitions
      mountPath: /etc/rabbitmq-definitions

  customScripts:
    ## @param rabbitmq.customScripts.postStart [object]
    ## load definitions after startup. The `definitions` key is not used since then we would have to add user & password
    ## into the definition file which isn't that easy
    postStart:
      enabled: true
      command:
        - sh
        - -ec
        - |
          sleep 5
          rabbitmqctl await_startup
          rabbitmqctl import_definitions /etc/rabbitmq-definitions/defs.json
    ## @param rabbitmq.customScripts.initContainers Custom init containers to run before RabbitMQ starts
    initContainers: []
