apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evaluator.fullname" . }}
  labels:
    {{- include "evaluator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "evaluator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "evaluator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "evaluator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "guggr.waitForPostgres" . | nindent 8 }}
        {{- include "guggr.waitForRabbitMQ" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          - name: RABBITMQ_HOST
            value: {{ include "guggr.rabbitmqHost" . | quote }}
          - name: RABBITMQ_PORT
            value: {{ .Values.global.rabbitmq.port | toString | quote }}
          - name: RABBITMQ_JOB_RESULT_QUEUE
            value: {{ .Values.global.rabbitmq.jobResultQueue | toString | quote }}
          - name: RABBITMQ_USER
            value: {{ .Values.global.rabbitmq.auth.username | toString | quote }}
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.rabbitmq.auth.secretName | quote }}
                key: {{ .Values.global.rabbitmq.auth.passwordKey | quote }}
          - name: POSTGRES_HOST
            value: {{ include "guggr.postgresHost" . | quote }}
          - name: POSTGRES_PORT
            value: {{ .Values.global.postgres.port | toString | quote }}
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.auth.secretName | quote }}
                key: {{ .Values.global.postgres.auth.databaseKey | quote }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.auth.secretName | quote }}
                key: {{ .Values.global.postgres.auth.usernameKey | quote }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.auth.secretName | quote }}
                key: {{ .Values.global.postgres.auth.passwordKey | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
