// Generated by diesel_ext (insertable structs)

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::{data_types::PgInterval, prelude::*};

use crate::schema::*;
#[derive(Insertable)]
#[diesel(table_name = group)]
pub struct NewGroup<'a> {
    pub name: &'a str,
}

#[derive(Insertable)]
#[diesel(table_name = job)]
pub struct NewJob<'a> {
    pub name: &'a str,
    pub job_type_id: &'a str,
    pub group_id: &'a str,
    pub notify_users: bool,
    pub custom_notification: Option<&'a str>,
    pub run_every: PgInterval,
    pub last_scheduled: Option<NaiveDateTime>,
}

#[derive(Insertable)]
#[diesel(table_name = job_runs)]
pub struct NewJobRun<'a> {
    pub job_id: &'a str,
    pub timestamp: NaiveDateTime,
    pub triggered_notification: bool,
    pub output: Option<&'a str>,
}

#[derive(Insertable)]
#[diesel(table_name = job_type)]
pub struct NewJobType<'a> {
    pub name: Option<&'a str>,
}

#[derive(Insertable)]
#[diesel(table_name = role)]
pub struct NewRole<'a> {
    pub name: &'a str,
}

#[derive(Insertable)]
#[diesel(table_name = user)]
pub struct NewUser<'a> {
    pub name: &'a str,
    pub email: &'a str,
    pub password: &'a str,
}

#[derive(Insertable)]
#[diesel(table_name = user_group_mapping)]
pub struct NewUserGroupMapping<'a> {
    pub user_id: &'a str,
    pub group_id: &'a str,
    pub role_id: &'a str,
}
