// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::{data_types::PgInterval, prelude::*};

use crate::schema::*;
#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(table_name = group)]
pub struct Group {
    pub id: String,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(table_name = job)]
pub struct Job {
    pub id: String,
    pub name: String,
    pub job_type_id: String,
    pub group_id: String,
    pub notify_users: bool,
    pub custom_notification: Option<String>,
    pub run_every: PgInterval,
    pub last_scheduled: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(table_name = job_runs)]
pub struct JobRun {
    pub id: String,
    pub job_id: String,
    pub timestamp: NaiveDateTime,
    pub triggered_notification: bool,
    pub output: Option<String>,
}

#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(table_name = job_type)]
pub struct JobType {
    pub id: String,
    pub name: Option<String>,
}

#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(table_name = role)]
pub struct Role {
    pub id: String,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(table_name = user)]
pub struct User {
    pub id: String,
    pub name: String,
    pub email: String,
    pub password: String,
}

#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(primary_key(user_id, group_id))]
#[diesel(table_name = user_group_mapping)]
pub struct UserGroupMapping {
    pub user_id: String,
    pub group_id: String,
    pub role_id: String,
}
