name: basic ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      rustBacktrace:
        description: 'Rust Backtrace'
        required: false
        default: '1'
        type: choice
        options:
          - '0'
          - '1'
          - FULL

permissions:
  contents: read

jobs:
  changes:
    name: 🎯 identify changes
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
      contents: read
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      pnpm: ${{ steps.filter.outputs.pnpm }}
      go: ${{ steps.filter.outputs.go }}
      helm: ${{ steps.filter.outputs.helm }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            rust:
              - agent/**
              - scheduler/**
              - evaluator/**
              - database/database-client/**
              - gen/**
              - '**/Cargo.toml'
              - '**/Cargo.lock'
              - '**/*.rs'
            pnpm:
              - pnpm-lock.yaml
              - package.json
              - frontend/**
              - '**/*.yaml'
              - '**/*.json'
              - '**/*.sql'
              - '!charts/**'
            go:
              - api-service/**
              - '**/*.go'
              - '**/go.sum'
              - '**/go.mod'
            helm: charts/**

  pnpm-lint:
    name: 🐛 formatting & linting - pnpm
    needs: changes
    if: ${{ needs.changes.outputs.pnpm == 'true' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
      #   cache: true - key will be available in next action release
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - name: Check
        run: pnpm check
  #      - name: Build
  #        run: pnpm build

  go-lint:
    if: ${{ false }} # wait for go setup so this does not fail
    name: 🐛 formatting & linting - go
    # needs: changes
    # if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version-file: 'go.work'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version-file: .tool-versions

  cargo-fmt:
    name: 🐛 formatting - cargo nightly
    runs-on: ubuntu-24.04
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    steps:
      - uses: actions/checkout@v6.0.2
      - run: rustup update nightly && rustup default nightly
      - run: rustup component add rustfmt --toolchain nightly
      - run: cargo +nightly fmt --check

  cargo-lint:
    name: 🐛 formatting & linting - cargo
    runs-on: ubuntu-24.04
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: protobuf-compiler
      - run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2.8.2
        with:
          cache-on-failure: true
      - run: cargo clippy --all-features --all-targets -- -D warnings

  helm-lint:
    name: 🐛 lint - helm
    runs-on: ubuntu-24.04
    needs: changes
    if: ${{ needs.changes.outputs.helm == 'true' }}
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: igabaydulin/helm-check-action@0.2.1
        env:
          CHART_LOCATION: ./charts
          CHART_VALUES: ./charts/values.yaml

  cargo-nextest:
    name: 🧐 testing - cargo
    runs-on: ubuntu-24.04
    needs:
      - cargo-lint
      - cargo-fmt
      - changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: protobuf-compiler
      - run: rustup update stable && rustup default stable
      - uses: cargo-bins/cargo-binstall@v1.17.4
      - run: cargo binstall cargo-nextest
      - uses: Swatinem/rust-cache@v2.8.2
        with:
          cache-on-failure: true
      - run: cargo nextest run --no-tests warn --all-features --all-targets
        env:
          RUST_BACKTRACE: ${{ inputs.rustBacktrace || '0' }}

  trufflehog:
    name: 🔐 secret scanning
    runs-on: ubuntu-24.04
    steps:
      - name: Calculate fetch depth
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
            echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v6.0.2
        with:
          ref: ${{env.branch}}
          fetch-depth: ${{env.depth}}
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3.93.0
        with:
          extra_args: --results=verified,unknown
