name: basic ci
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  pnpm-lint:
    name: 🐛 formatting & linting - pnpm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
      #   cache: true - key will be available in next action release
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - name: Check
        run: pnpm check
  #      - name: Build
  #        run: pnpm build

  go-lint:
    if: ${{ false }} # wait for go setup so this does not fail
    name: 🐛 formatting & linting - go
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version-file: 'go.work'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version-file: .tool-versions

  cargo-fmt:
    name: 🐛 formatting - cargo nightly
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - run: rustup update nightly && rustup default nightly
      - run: cargo +nightly fmt --check

  cargo-lint:
    name: 🐛 formatting & linting - cargo
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - run: rustup update stable && rustup default stable
      - uses: taiki-e/install-action@v2.9.4
        with:
          tool: nextest
      - run: cargo nextest run --no-tests warn
      - run: cargo clippy
      - run: cargo build --release

  helm-lint:
    name: 🐛 lint - helm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: igabaydulin/helm-check-action@0.2.1
        env:
          CHART_LOCATION: ./charts
          CHART_VALUES: ./charts/values.yaml

  trufflehog:
    name: 🔐 secret scanning
    runs-on: ubuntu-24.04
    steps:
      - name: Calculate fetch depth
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
            echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v6.0.2
        with:
          ref: ${{env.branch}}
          fetch-depth: ${{env.depth}}
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3.93.0
        with:
          extra_args: --results=verified,unknown
