name: basic ci
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  commit-pr-lint:
    name: 🐛 conventional commits & pr
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: webiny/action-conventional-commits@v1.3.1
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.5.1
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          custom_labels: '{"feat": "enhancement", "fix": "bug", "docs": "documentation", "test": "test", "ci": "ci", "refactor": "refactor", "perf": "performance", "chore": "chore", "revert": "revert", "wip": "wip"}'
        if: github.event_name == 'pull_request'
